### ISSUE TITLE
@iconify/react addCollections being called, but still loading from API? 

### ISSUE THREAD

**Issue by bwhite94** [iconify/iconify#101]
After the move to webpack v5, I'm seeing my `@iconify/react` `<InlineIcon>` components are attempting to load my 'custom' fonts from the Iconify API provider, despite having called addCollection() at the initialization of my app.

JSON collection:
```
{ prefix: "custom", icons: { "leaf": {"body": "<path d=\"  ...  } } }
```

App initialization, this is called prior to the first render of any component:
```
import customFont from './path-to-file/custom.json';
import { addCollection } from '@iconify/react';

function initialize()
{
    addCollection(customFont)
}
```

Usage:
```
import { InlineIcon } from '@iconify/react';

...

render()
{
    return ( <InlineIcon icon="custom:leaf" /> );
}
```

Is anyone else experiencing a similar issue? The rest of our application bundling appears to work as expected.

**Comment by cyberalien** [comment]
Code looks good. Maybe function `initialize` is not executed?

**Comment by bwhite94** [comment]
Thanks for the quick response! The initialize function is being called as I have a breakpoint on load, and I am able to inspect the values of the custom font as expected. I saw there were some changes to API icon loading in the November changelog but I wasn't sure. I'm thinking it may be more related to webpack's JSON module support with v5, but I wanted to make sure I wasn't missing any changes for collection management. 

Is there someway to tap into available collections in the `@iconify/react` package to rule out a timing issue? Since I'm able to see these values loaded in the bundle from my collection's JSON and the add collection being called, I'm not sure why it would be making requests to the below:
1. api.iconify.design/custom.json?icons=leaf 
2. api.simplesvg.com/custom.json?icons=leaf
3. api.unisvg.com/custom.json?icons=leaf

**Comment by cyberalien** [comment]
Maybe component is being rendered before init function is called? That would trigger loading from API because at the moment of rendering that icon data is not available.

As for requests, it is a redundancy feature. Internet is not reliable, sometimes things do go wrong, so if component cannot load data from `api.iconify.design`, it attempts to load it from backup API.

**Comment by bwhite94** [comment]
Closing this for now, since I believe this is more related to webpack changes. Thanks for the assistance @cyberalien!

**Comment by bwhite94** [comment]
Our application is using an iconify collection generated and imported from a custom package. It seems either the registry used by different packages are different by default after the move to webpack 5. I'm not really sure how this would differ, though.

Repo A (Packaged and required in Repo B):
- declared init function with logging and custom.json for icon collection to be added

Repo B:
- Called init function from repo B in boot strapping process (logging occurs)
- Utilize `iconExists()` from the `@iconify/react` package to determine the icon is not loaded in Repo B

I have logging in place to ensure the collection is being loaded prior to the component being rendered, but the init function is declared in a separate package and called during runtime. I see the custom icons loading fine in the components exported from that package, but within the top-level project it is not finding the collection.

Is there a way to override the "registry" to ensure the `@iconify/react` components are pointing to the same icon sets?

**Comment by cyberalien** [comment]
Component is self contained, it does not create global variables. That means if you have multiple copies of it, each copy has its own storage.

I'll try to think of a workaround.

**Comment by cyberalien** [comment]
I think polluting global variables is not acceptable as default behaviour, but can be used as an option for edge case. So I came up with this solution:

Added new function `shareStorage` that copies data storage to global variable `_iconifyStorage`. All new instances will check if that variable exists and use storage from it. Since existence of variable is checked only during initialisation, run `shareStorage` synchronously in a bundle, so bundle with different copy of component will detect it during load.

```js
import { shareStorage, addCollection } from '@iconify/react';

shareStorage();
addCollection(...)
```

Test version is available with tag `dev`: `npm install @iconify/react@dev`. Please post here if it solves your problem.

**Comment by bwhite94** [comment]
That solves the issue! I'm not sure what may have changed prior to webpack 5, but with this addition it solves this issue.

**Comment by cyberalien** [comment]
Awesome. I'll keep this for now as a temporary solution, will create proper tests to test it all (should be a challenge in itself because it can only be tested in real browser), then will publish this as `latest` version of all components.

In future I think this function will be removed. Instead I'll attempt to share all data between instances, including functions. But that's an idea for next major version of components, not minor version.

**Comment by bwhite94** [comment]
Thank you for the quick responses! Would you mind tagging this issue once it's published to `latest`?

**Comment by cyberalien** [comment]
Sure

**Comment by cyberalien** [comment]
> Thank you for the quick responses! Would you mind tagging this issue once it's published to `latest`?

It has been published to `latest`.
