### ISSUE TITLE
[serving feature] Support Cross Origin Resource Policy for hosted js script

### ISSUE THREAD

**Issue by qortex** [iconify/iconify#128]
In order to be able to use the iconify script with the `<script>` tag and with [Cross Origin Embedder Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Embedder-Policy) enabled (good security practice), the iconify server would be required to respond with the [Cross Origin Resource Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)) set to 'cross-origin'.

Is it something doable on your side?

**Comment by cyberalien** [comment]
I'm not sure. Whole thing is a bit confusing.

Currently Iconify website sends `Access-Control-Allow-Origin: *` header, allowing anyone to embed it.

If I understand correctly, you need it to also send `Cross-Origin-Resource-Policy: cross-origin`?

**Comment by qortex** [comment]
Yes, just discovered that yesterday also, upgrading to Helmetjs v5 started to make the `script` embed invalid because of the default policies, so I started to investigate.

If I understand correctly, a resource has a new (?) way of telling browsers if it can be embedded into another website or not. It must be useful to avoid some kind of cross-site attacks.

Then, an app can run in two modes: with *cross origin embedder policy* enabled or not.

When it is enabled, the browser must verify that any external resource has a `Cross-origin-resource-policy` header that allows it to be embedded.

When it is disabled, all resources are accepted.

To make the `script` approach work again, I just disabled the cross origin embedder policy.

I use the `script` approach because my app is an Angular app.

For a script like iconify that can be safely imported into any site, I think a `Cross-Origin-Resource-Policy` set to `cross-origin` would be the correct setting.

Hope I understand the whole thing correctly :)

**Comment by cyberalien** [comment]
Thanks. I'll need to test it to make sure it doesn't break anything for everyone else, but so far it looks like it is doable.

**Comment by userquin** [comment]
@cyberalien @qortex using popular cdn returning this headers (last 3 not required: for example google fonts send them):
```md
access-control-allow-origin: *
cross-origin-resource-policy: cross-origin
access-control-expose-headers: *
cross-origin-opener-policy: same-origin-allow-popups
timing-allow-origin: *
```

Check headers for these urls: 
- https://fonts.googleapis.com/css2?family=Readex+Pro:wght@200;400;600&display=swap
- https://cdn.jsdelivr.net/gh/antfu/static/sponsors.svg

I have had problems using some cdn with pwa and opaque resources: with previous headers the problem disappear (some `crossorigin="anonymous" attr required).

**Comment by cyberalien** [comment]
Thanks!

I've set those headers on different website to avoid breaking main website in case things go wrong.

Can you check it to make sure it works? Instead of `http://code.iconify.design/2/2.1.0/iconify.min.js` in script tag try `https://test.artodia.com/iconify.js`. First URL should fail, second URL should work.

**Comment by cyberalien** [comment]
Tested differences with and without header. It does fix issue and doesn't break anything for users that do not use cross-origin headers. Added headers to `code.iconify.design`.

It will take a while to add them to API because there are many servers. Each of them needs to be temporarily taken out of network to update nginx config and I want to start with server in Frankfurt that is closest to me so I could see changes immediately, which should be done early in the morning when traffic is lowest. So I'll start working on that tomorrow.

**Comment by qortex** [comment]
Brilliant, thanks a lot!

**Comment by cyberalien** [comment]
Done. All API servers are now sending `Cross-Origin-Resource-Policy: cross-origin` in addition to other CORS headers.
