### ISSUE TITLE
Defining behavior in vue2 application

### ISSUE THREAD

**Issue by gitgkk** [iconify/iconify#141]
Hi,

I like this library, this seems to be the most complete collection of mdi icons. Thanks for the great project. I downloaded it and installed for offline use.

1. I'm unable to find a way to define onMouseHover behavior, wherein a menu can be displayed. How should I achieve this?
2. Do we have to always wrap the icon in a component to use, like it is in the vue 2 checkbox demo? How can I use it with v-menu for onHover or onClick?

Thanks for the help.
Kashyap

**Comment by cyberalien** [comment]
Events are not passed because it is hard to do for a functional component. So there are 2 alternative options you can try that might work with events without wrapping: `unplugin-icons` or `iconify-icon`.

Since you are using it without API functionality, you can try `unplugin-icons`: https://github.com/antfu/unplugin-icons It is different component that bundles all icon data, so it is like offline component but without extra overhead. I think it works with events.

Another option is `iconify-icon`: https://www.npmjs.com/package/iconify-icon It is currently in development. It is not a Vue component, it is a web component, so it might require additional steps to make it work with Vue. Functionality is similar to `@iconify/vue`: same `addIcon()` and `addCollection()` functions, icon can be used by name.

**Comment by gitgkk** [comment]
Thanks, will try!
