### ISSUE TITLE
Change the weight of material symbols

### ISSUE THREAD

**Issue by ldsenow** [iconify/iconify#160]
Is there a way to use a different weight of material symbols icons?

**Comment by cyberalien** [comment]
Not right now.

Unfortunately source icons with stroke that are used to generate various weights are not available, Google developers published only finished icons that use fill. This means there is no way to generate various weights and each icon + weight combination has to be treated separately.

Regular weight fits nicely in 24x24 grid. There are over 8k unique icons, though actual number of files is almost twice higher, but there are many identical icons with different names.

Other weights are not designed for any grid, they look blurry on regular monitors. So those are bad icons.

In addition to being bad icons, there are other issues with them:
- Import / update process is already slow because Google developers don't publish files. Their GitHub repository is almost always outdated and barely maintained, so files need to be fetched from Google servers, one by one.
- Huge number of icons. Actual number of icons is over 100k, though with removal of duplicates it would be much smaller number, it is still a huge number. It would flood search results with duplicates of same icon with different weights. API needs to be updated to ignore those icons, but it would still require large amount of memory to keep all those variations in memory to serve data to icon components.

So I'm not in favour of importing those variations.
