### ISSUE TITLE
Accessibility support?

### ISSUE THREAD

**Issue by mcanouil** [iconify/iconify#162]
Is there any option to support accessibility to screen readers, etc.?

**Comment by cyberalien** [comment]
That depends on what package you are using.

Older packages don't really support it. You can add `title` attribute, but browsers don't show it, so it needs to be added to parent element. That's because of how browsers handle `title` attribute in SVG. Other attributes, such as `aria-` attributes are supported.

In new `iconify-icon` web component everything works correctly: `title`, `aria-` attributes. So you can use it to add text for screen readers:
```
<iconify-icon icon="fluent-emoji:smiling-face" title="Smiling face emoji"></iconify-icon>
```

**Comment by mcanouil** [comment]
I see, so I have to change from using: `<span class="iconify" data-icon="fluent-emoji:astonished-face"></span>` and `<script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>`.

I did not see about the web component you described in the gallery (<https://icon-sets.iconify.design/fluent-emoji/astonished-face/>), where can I find the documentation?

**Comment by cyberalien** [comment]
Web component is a newer replacement for SVG framework. See https://docs.iconify.design/iconify-icon/

So instead of `<span class="iconify" data-icon="fluent-emoji:astonished-face"></span>` write code I posted above.

Instead of 
```html
<script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>
``` 
use 
```html
<script src="https://code.iconify.design/iconify-icon/1.0.0-beta.2/iconify-icon.min.js"></script>
```

**Comment by mcanouil** [comment]
Perfect, I'll try that and update my code with that.

**Comment by mcanouil** [comment]
Thanks, it works smoothly and it is even better.
https://github.com/mcanouil/quarto-iconify/pull/4
