### ISSUE TITLE
URL does not update when searching in an icon set

### ISSUE THREAD

**Issue by kidonng** [iconify/iconify#165]
If I search "keyword" in all icons, the URL will correctly update to `https://icon-sets.iconify.design/?query=keyword`.

But if I search "keyword" in an icon set, the URL stays at `https://icon-sets.iconify.design/icon-set-name/`. Though manually adding `?query=keyword` still works.

**Comment by cyberalien** [comment]
That's by design.

When you search all icons, query is sent only when you submit form, so it is a separate page.

When you search icons in icon set, page is not changed, UI just filters existing icons list and it does that on every key stroke as you type. So for example, for `keyword` it would result in 7 pages starting with `k`, then `ke` and so on. So it would require special handling to compare to previous entry in history and replace URL instead of appending it.

Current version of website is based on old spaghetti code, which is hard to manage. I'm in process of rewriting it, but for current code it is hard to implement.

Added this to todo list for new version. Thanks for suggestion!

**Comment by kidonng** [comment]
This is enough to work:

```js
addEventListener('input', (event) => {
    if (!event.target.matches('.iif-view--collection .iif-input input')) return
    const url = new URL(location.href)
    const {value} = event.target
    if (value) url.searchParams.set('query', value)
    else url.searchParams.delete('query')
    history.replaceState(null, '', url.href)
})
```

> Current version of website is based on old spaghetti code, which is hard to manage. I'm in process of rewriting it, but for current code it is hard to implement.

I get that a bit after reading https://github.com/iconify/iconify/issues/20#issuecomment-657022853. I don't mean to be demanding! I proposed these issues as the website is not open source (yet?), so I can not contribute these myself. But they are easy to implement (hence I'm posting code here) and bring some quality of life features I'm sure lots will enjoy.
