### ISSUE TITLE
SvelteKit SSR behaviour

### ISSUE THREAD

**Issue by kryptn36** [iconify/iconify#178]
I'm using the example svelte component from [here](https://docs.iconify.design/icon-components/svelte/load-icons.html)

On further initial page loads (after closing the browser) the icons still get requested from the api even if the icons are rendered by the server.
This causes the icons to flicker. Can this behaviour be disabled somehow?

See the screenshot [here](https://i.imgur.com/YTqjOFm.png).

**Comment by cyberalien** [comment]
That's normal behaviour. Icon rendered on server and in browser are two completely separate rendering events. Data sent by SvelteKit only includes component, not icon data, even though it was retrieved on server because icon data is not part of component.

If you want icon to be rendered on server and be displayed immediately in browser, best option is to use `unplugin-icons`. It behaves exactly the way you are expecting, doesn't add any overhead.

**Comment by janosh** [comment]
Not so nice thing about `unplugin-icons` is every icon becomes it's own import. `@iconofy/svelte` is cleaner as you import a single icon component and pass it whatever icon ID. Would be cool if `@iconofy/svelte` could support inlining icon SVG out of the box!

**Comment by cyberalien** [comment]
Unfortunately SSR causes a big headache when working with dynamically loaded data. When component is used on both server and client, render result must match, otherwise hydration process fails.

How to make data match?

Option 1: render identical SVGs. That is a problem because:
- If icon data is not available in either server or client on initial render, it will fail.
- If icon includes unique IDs, such as clip paths, masks or gradients, IDs are supposed to be unique, so rendering same icon in multiple locations should render different content with different IDs. There is no way to make sure IDs are identical in client and server rendered icons, so such icons will cause hydration to fail.

Option 2: render nothing on initial load, render actual icon only when component is mounted. This solves hydration issue because both server and client render nothing, also helps reduce initial load because SVGs are not embedded in HTML sent by server. Downside is, icon is not rendered instantly, causing flicker.

Option 3: use web component: `iconify-icon` package (works with Svelte, SvelteKit). It is rendered separately from framework, actual content is in shadow DOM, so no need to worry about hydration, mounting or unique IDs. Really good for server side rendering. However, it also has a downside: web component is created asynchronously, which is by design specified in web component spec, so even if web component instantly renders data, render might be delayed.

So unfortunately all options have downsides.

I'm currently experimenting with a different option: rendering icon as style, similar to UnoCSS, but loaded dynamically. Maybe it will solve issues, I don't know yet, but hoping it will.

**Comment by janosh** [comment]
@cyberalien Could you point me at the relevant commit that closed this? Wondering what needs to change on my end.

**Comment by cyberalien** [comment]
There is nothing to change. I have explained this behaviour, why it happens and alternatives.

**Comment by janosh** [comment]
I see. I was confused because you closed as completed. Maybe closed as not planned would be more accurate?
