### ISSUE TITLE
Should xmlns attributes not be omitted from inline SVGs?

### ISSUE THREAD

**Issue by Arturexe** [iconify/iconify#180]
Loving your app so far. I'm using the iconify site to paste raw `SVG code` inline into `HTML`. For that purpose `xmlns` attributes seem redundant. Would it not make sense to omit `xmlns` attributes from the `inline SVG code`? And for users who want to use `.svg images`, there is the `download button` right below the SVG, which can keep the `xmlns` attributes.

**Comment by cyberalien** [comment]
It is required. Browsers can render icons without it, except for few cases such as using it as background or mask, but browsers can render all kinds of other invalid code code.

This should help you understand why it is required: https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course

Even if it was optional for inlining SVG, I'd still keep it because in some cases it is required. There are already too many code sample options, vast majority of users don't even understand differences between those options. Adding extra options for SVG with and without namespace would only cause confusion, users copying wrong icon then wondering why it doesn't work. Putting any explanation near code sample doesn't solve it because users rarely read that.
