### ISSUE TITLE
Request to add Iconify news feed

### ISSUE THREAD

**Issue by jameschensmith** [iconify/iconify#182]
#### Summary

I'd ~~like~~ love to subscribe to Iconify updates. For other repositories, I tend to use `https://github.com/:owner/:repo/releases.atom` to subscribe to releases, but I see that Iconify doesn't do GitHub releases. I'm aware of the [news page](https://iconify.design/news/) on Iconify, but I don't see an RSS/Atom feed for it. I prefer release feeds, but a feed of the current news page would also work.

**Comment by cyberalien** [comment]
Problem is, this monorepo has many packages, each package uses its own version numbers. Release requires one version number.

**Comment by cyberalien** [comment]
Yes, that might be possible. Need to think about how to automate updates, also it probably can use filters, so you can select which packages you want to see feed for.

**Comment by cyberalien** [comment]
While idea sounded good at first, it is a rare use case, but it requires a lot of development time.

This can already be achieved by watching NPM for updates. There are third party tools for that. Not sure if they can do RRS/Atom, but if not, that's an idea for a different project. Either way, it is out of scope for this project.

**Comment by cyberalien** [comment]
yes, that's a very good idea!

**Comment by cyberalien** [comment]
To help you understand how news works on new website. All news are stored in `news/{year}/{file}`, where `{year}` is year, `{file}` is a separate file for each news item.

Filename for news ends with either `.md` or `.html` and name means one of:
- `16.05` -> `{day}.{month}`
- `1642688466` (10 digits) -> UTC time stamp in seconds (as generated by PHP, since old website was using PHP)
- `1642688466000` (13 digits) -> UTC time stamp in milliseconds (as generated by Date.now() in JavaScript)

Each news file includes metadata, which includes title and link. See `scripts/news.mjs` for function `parseNewsArticle()` that parses all possible formats and returns simple to use object, which contains title, link, time (as Date object), content.

**Comment by jameschensmith** [comment]
Awesome! Great information to have on the file names, by the way. Really appreciate that. I'll get started on this, and will reach out to you once it's done, or if I need another tip on the code base like the one above.

Also, not sure if you like moving issues, but this could possibly be moved to `iconify/website` now as well.
