### ISSUE TITLE
SVG element not showing!

### ISSUE THREAD

**Issue by wpplumber** [iconify/iconify#212]
I'm using npm 16 and version `4.1.1 `with `Vue 3` and `Astro` but the SVG not showing!

![image](https://user-images.githubusercontent.com/52907282/229340047-2d14deff-26c4-463c-be9b-6fb79b972eac.png)

**Comment by cyberalien** [comment]
What code are you using for that icon?

**Comment by wpplumber** [comment]
Welcome, I'm using Composition API.

```
import { Icon } from '@iconify/vue';

...
 components: {  Icon },
..
```

Template:
`<Icon icon="mdi:account-box-outline" :inline="true" />`

**Comment by cyberalien** [comment]
That usage is correct. So either icon data is failing to load or mount event isn't called.

Are you checking actual icon as it is rendered in browser or HTML code sent by Astro?

**Comment by wpplumber** [comment]
In Astro it works but SFC in Vue 3 not working!

**Comment by cyberalien** [comment]
Can you make a test repo, or alternatively, debug it?

In `dist/iconify.mjs` (or .js if you are using commonjs) find this:
```js
render() {
```
few lines below it you should see this:
```js
 const icon = this.iconMounted
            ? this.getIcon(props.icon, props.onLoad)
            : null;
```
add this after it:
```js
console.log(
			`rendering ${
				typeof props.icon === 'string' ? props.icon : typeof props.icon
			}. mounted: ${this.iconMounted ? 'yes' : 'no'}, data: ${
				icon ? 'exists' : 'missing'
			}`
		);
```

It should log several entries for each render:
```txt
rendering mdi-light:alert. mounted: no, data: missing
```
for first render before icon is mounted,
```txt
rendering mdi-light:alert. mounted: yes, data: missing
```
after icon is mounted if icon data is not cached (will be missing if icon data is already loaded),
```txt
rendering mdi-light:alert. mounted: yes, data: exists
```
last entry when icon is mounted and data is available.

**Comment by Zlendy** [comment]
Hi @cyberalien 

I just happened to stumble across this bug, here's a minimal [codesandbox](https://codesandbox.io/p/sandbox/kind-brown-pryq3t) to reproduce it.

Apparently it only works when Astro hydrates the component using the `client:load` directive.

**Comment by cyberalien** [comment]
Thanks for reproduction! I can see issue there.

Component is rendered on server, but component is not mounted. That is expected SSR behaviour of Iconify icon component (see below).

However, it is never re-rendered in client. So hydration doesn't happen. I think that's just how Astro works. If so, there is nothing to do because it is Astro's behaviour that is causing this.

So why is component not rendering anything on server? For several reasons.

1. This icon component is supposed to load data on demand from API. If you are rendering icons on server, why are you using this component in first place? You don't need to load data, you are already sending it from server.

2. Hydration and unique ids. In frameworks like Nuxt, Next, SvelteKit and others, they expect content rendered on server to match content rendered in browser, otherwise hydration might fail. Problem with icons is they can have unique ids for things like clip paths, masks, filters, animations and many other things. Those ids must be unique, so 2 icons can't have same ids. This means using same icon in multiple locations will result in errors. To avoid that, Iconify components randomise ids for each icon. This causes an issue with hydration: data rendered on server might not match data rendered in browser. So to solve that, icon component doesn't render anything until it is mounted. This way nothing is rendered on server, actual icon is rendered only in browser, not causing any conflicts.

Back to issue. Issue is Astro is not rendering anything on client. That's an Astro issue, nothing I can fix. Looks like `client:load` is correct way to deal with it.

If you do want icon to be rendered on server, you are using wrong component. You need to use solution that bundles icons: Unplugin Icons, UnoCSS or just copy SVG from Iconify website.

Thanks a lot for reproduction! I helped me understand what is going on, but there is nothing to fix.

**Comment by Zlendy** [comment]
That's certainly a bummer. But I'm grateful that you took the time to explain what the issue is, I really appreciate it!
