### ISSUE TITLE
Problem with Content Security Policy: require-trusted-types-for 'script'

### ISSUE THREAD

**Issue by silvio-e** [iconify/iconify#229]
Hello, I have a problem in a project where the CSP `require-trusted-types-for 'script'` is enabled. If I understand it right because Iconify uses `innerHTML`, it throughs following error in Chrome:

```console
This document requires 'TrustedHTML' assignment.
```

Do you know how to solve this problem besides removing the policy?

**Comment by cyberalien** [comment]
Description of that policy is very vague and uses example when assigning code with script, so I have no idea what's going on there.

As I understand, that policy affects only code that contains scripts, so it should not be triggered by icons because they are very strictly validated to make sure they do not contain scripts and other nasty stuff.

**Comment by cyberalien** [comment]
What icon component are you using and how are you using it (bundling or linking to external script)?

**Comment by cyberalien** [comment]
I think I found a fix. Can you please check if it works for you by installing `@iconify/react@next`?

**Comment by cyberalien** [comment]
New versions of React component, web component and SVG framework have been published with workaround for policy.

That policy is absolutely useless though. It should not be relied upon for any kind of security because it doesn't provide any. Whoever is using it is either misunderstanding it (most likely) or just saw word "security" (then its plain incompetence) and added it without understanding how it works. This explains this is first time I'm hearing it even though this policy existed for about 4 years, as most website developers are usually competent enough to read spec and understand that this policy is junk.

Why is it useless? Policy works by requiring content to be sanitised. However, it does not define how content is sanitised, does not provide any functions for doing it. It is up to a library to sanitise content. That means library can just return original string without doing any actual sanitisation. How is that considered "security"??? Absolutely useless policy.

**Comment by silvio-e** [comment]
Awesome! I'm sorry for not getting back to you sooner! It works great now! Thank you very much! 🙏 😊
