### ISSUE TITLE
Disable cache

### ISSUE THREAD

**Issue by VikingTristan** [iconify/iconify#233]
Sup! Great project!

Quick question: When disabling cache with `disableCache("all");`, should the `iconify-version` and `iconify-count` also not be set?

A very detailed and nitpicky thing, but some clients wants all keys to be explained due to GDPR constraints.

**Comment by cyberalien** [comment]
That cannot be changed. It is set when component is initialised, before cache can be disabled.

If you want to disable caching because of GDPR, I suggest to consider a different approach. Bundle all icons with Unplugin Icons or use them in CSS with various solutions.

API resources are not unlimited, caching helps reduce API usage, save bandwidth for users and render icons faster. Function to disable cache is not intended to help with GDPR, but to avoid storing way too much data in applications that load many icons, such as websites that search/browse icons.

**Comment by VikingTristan** [comment]
Alright!

> Bundle all icons with Unplugin Icons or use them in CSS with various solutions.

Thx for the tip
