### ISSUE TITLE
How about make tailwind plugin intelligent like @egoist/tailwindcss-icons

### ISSUE THREAD

**Issue by yunsii** [iconify/iconify#241]
I want to use [@iconify/tailwind](https://github.com/iconify/iconify/tree/main/plugins/tailwind) with intelligent and add custom icon set, so how about of this?

If possible I can make a PR for it.

**Comment by cyberalien** [comment]
It can accept custom icon sets in `iconSets` option: https://iconify.design/docs/usage/css/tailwind/options.html

**Comment by yunsii** [comment]
> It can accept custom icon sets in `iconSets` option: [iconify.design/docs/usage/css/tailwind/options.html](https://iconify.design/docs/usage/css/tailwind/options.html)

I know how to **custom icon sets**, meanwhile, I also want the feautre **"classname intelligent"** integrated, like:
![](https://user-images.githubusercontent.com/8784712/219618866-e5632d23-b948-4fa1-b3d6-00581a704bca.png)

**Comment by cyberalien** [comment]
That VSCode plugin does not parse config files, so it cannot show custom icons. It only shows available open source icons.

**Comment by cyberalien** [comment]
Actually... wrong response, I thought it was a different plugin. But still it is not possible, just for different reason.

That VSCode plugin shows available selectors that are basic selectors, but icons in Iconify plugin are dynamic selectors. Making them static, like heroicons in your screenshot, is not possible because there are about 150k icons.

It might work with `addCleanIconSelectors` plugin though because it does generate all rules for selected icons: https://iconify.design/docs/usage/css/tailwind/clean.html, but you need to know which icons you want to use and configure it.

**Comment by yunsii** [comment]
https://github.com/egoist/tailwindcss-icons/blob/044a7c5bbaf572dabb0afd6001cf396918c8c358/src/index.ts#L23-L35
![image](https://github.com/iconify/iconify/assets/18096089/203a5309-0707-4ae1-9918-92928fa968dd)

https://github.com/iconify/iconify/blob/4765dc962fc048a72496c8dc0c80d273eb3422a5/plugins/tailwind/src/plugin.ts#L12-L19

The difference of the 2 plugins: `@egoist/tailwindcss-icons` `matchComponents` with option `values`. I thought it make classname intelligent happen by tailwind vscode plugin, and I tried.

Moreover, I found that heroicons has 800+ icons
![image](https://github.com/iconify/iconify/assets/18096089/14d069cc-9f23-4f55-929c-34642494fdd6)

So how about add option (like `intelligent`) to make `addDynamicIconSelectors` work with classname intelligent by tailwind vscode plugin?

**Comment by cyberalien** [comment]
Big difference is `@egoist/tailwindcss-icons` creates selectors for all icons. It has to be done because Tailwind CSS generates all possible selectors first, so plugin must generate CSS for thousands of icons, then it picks ones that are used in current project.

If autocompletion is a must have, you can use `@egoist/tailwindcss-icons`, it is a very good option and looks like it fits perfectly for your use case.

**Comment by yunsii** [comment]
I want both of benifits:
- autocompletion
- custom icon set

Since it is so, I'm trying to fork [@iconify/tailwind](https://github.com/iconify/iconify/tree/main/plugins/tailwind?rgh-link-date=2023-08-13T05%3A08%3A09Z) and add what I want 😶‍🌫️

**Comment by cyberalien** [comment]
You can use that plugin with custom icon sets too. `collections` parameter is list of icon sets, so you can assign `IconifyJSON` object to custom prefix.

**Comment by yunsii** [comment]
> You can use that plugin with custom icon sets too. `collections` parameter is list of icon sets, so you can assign `IconifyJSON` object to custom prefix.

Great, but I have publiched my package [https://github.com/yunsii/tailwindcss-plugin-iconify] 😂 and `@iconify/tailwind` has `overrideOnly` feature. I will use my package firstly, and it will deprecated at the right time if possible.
