### ISSUE TITLE
Adding TDesign Icons Collection

### ISSUE THREAD

**Issue by insub** [iconify/iconify#247]
Hi, is it possible to add this set of svg as iconset TDesign? This is an open source svg icon library of Tencent Co. MIT licenses.
[https://github.com/Tencent/tdesign-icons](https://github.com/Tencent/tdesign-icons)
[https://www.npmjs.com/package/tdesign-icons-vue](https://www.npmjs.com/package/tdesign-icons-vue)
[https://www.npmjs.com/package/tdesign-icons-vue-next](https://www.npmjs.com/package/tdesign-icons-vue-next)

**Comment by cyberalien** [comment]
Icons do look very good. I'll add it tomorrow.

Many icons contain invalid clip paths, which results in broken code, but it can be fixed automatically, so icon set can be imported.

**Comment by cyberalien** [comment]
Added: https://icon-sets.iconify.design/tdesign/

**Comment by insub** [comment]
Thank you very much!
But if possible, would it be possible to consider modifying the prefixes of the icons to be slightly shorter for ease of use? Like remixicon -> ri:
"td:" I wonder if that's possible?

**Comment by cyberalien** [comment]
Sorry, not after it was added. It would require creating new icon set and deprecating old one, so duplicating it.

**Comment by insub** [comment]
duplicating it? pardon me, but how？

**Comment by cyberalien** [comment]
Once icon set is created, packages are created for it with prefix in package name, users might start using icons with that prefix.

To rename icon set, it needs to be re-created using new prefix. But then what happens to old prefix? Old prefix remains because otherwise things might break for users who use that set with old prefix. That results in duplication: same icons with old and new prefix.

In this example I don't see how `td` or `tde` would be fitting for that icon set. It is not use anywhere in icon set, so it doesn't fit. When icon set author asks to add icon set to Iconify, I ask for preferred prefix, so it can be agreed upon before icon set is added. But you are not author of that icon set.

**Comment by insub** [comment]
@cyberalien Okay, I understand now, thanks
