### ISSUE TITLE
svelte OfflineIcon broken with 3.1.6

### ISSUE THREAD

**Issue by Conni2461** [iconify/iconify#265]
Bumping from 3.1.4 to 3.1.6 seems to break `import Icon from "@iconify/svelte/dist/OfflineIcon.svelte";` and `import Icon from "@iconify/svelte/offline";
` also doesnt seem to work.

Is Offline still supported? or do i do something wrong, not sure right now

**Comment by cyberalien** [comment]
It was removed because of build and usage issues.

Offline component was created when there were no other solutions for using icons without API. Today this is no longer needed because new solutions are available for that: Unplugin Icons, UnoCSS, Tailwind plugin, multiple libraries and functions to generate icons during build process. Compared to any of those solutions, offline component is performing much worse: it includes icon data and various functions for rendering it, while other solutions include only icon data.

I recommend switching to any of those solutions, Unplugin Icons is the most suitable replacement.

**Comment by Conni2461** [comment]
okay thanks for the heads up, ill look into other solutions
