### ISSUE TITLE
Workerd SSR issues

### ISSUE THREAD

**Issue by zsilbi** [iconify/iconify#285]
Hello!

I opened an issue in the [nuxt-icon](https://github.com/nuxt-modules/icon/issues/142) module recently about this problem.

It uses the `loadIcon()` method from `@iconify/core` which causes problems when rendering our sites on Cloudflare Workers.
There is a limitation in the worker runtime where promises created in one request, cannot be referenced in another.

My guess is when multiple workers start/render in the same region, and request the same icons they will end up awaiting promises that were created in another context.

When this happens it results in a fatal error in the Worker itself, and there is no way to catch that in the application.
This is relatively rare, but we experienced more than 250 failed requests daily because of this on a high traffic site.

I made a minimal reproduction for that issue: https://github.com/zsilbi/nuxt-icon-workerd

Then I [added a seperate test](https://github.com/zsilbi/nuxt-icon-workerd?tab=readme-ov-file#testing-iconifycore-loadicon) that calls only the `loadIcon()` method once in a worker wihout Nuxt, but this way the worker instantly throws an error on every request:
```
✘ [ERROR] A hanging Promise was canceled. This happens when the worker runtime is waiting for a Promise 
from JavaScript to resolve, but has detected that the Promise cannot possibly ever resolve because all code 
and events related to the Promise's I/O context have already finished.
```

My current workaround is to use the icons only on the client side, but I hope there is a solution to this.

Thanks,
zsilbi

**Comment by cyberalien** [comment]
Icon is not rendered on server side anyway, it is rendered only when component is mounted, so using it as client only component does not change anything. It behaves that way precisely because of SSR to avoid breaking hydration as it is designed to be a client only component.

Solution is to switch to `iconify-icon` package instead of `@iconify/vue`. It is a web component, which solves SSR shenanigans.

See https://github.com/nuxt-modules/icon/issues/139
