### ISSUE TITLE
Icon not showing in simple JavaScript

### ISSUE THREAD

**Issue by aminya** [iconify/iconify#30]
I am trying to use iconify but I cannot. Is this correct? Nothing shows for me. What should I do with `Iconify` after import? The documentation is very vauge.
```js
import Iconify from '@iconify/iconify';
export function createIcon(iconName) {
  const icon = document.createElement("div");
  icon.innerHTML = `
    <span class="iconify" data-icon="${iconName}"></span>
  `
  return icon
}
```

![image](https://user-images.githubusercontent.com/16418197/88476461-22423200-cefe-11ea-9019-376140ff5e8f.png)

**Comment by antfu** [comment]
If you are able to use it without a bundler, you can simply add this line to your header
```html
<script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
```

**Comment by aminya** [comment]
I do not have an HTML file to include this in. I am writing a package for Atom which is written inside Electron. I am using Rollup, but I declared iconify as external so the bundler does not make a difference. 

See this to know what I am talking about: https://github.com/suda/tool-bar/pull/310/files. I switched to @mdi/js here, however, I was wondering if I can use iconify which allows me to have access to all of the icons.

**Comment by antfu** [comment]
I am not very familiar with the import usage. Trying to pin @cyberalien here and I think he may able to help you :)

**Comment by cyberalien** [comment]
That is expected behavior. Script scans DOM for placeholder. Your node
isn't in DOM yet, so script cannot find it.

I'll see if it would be possible to add functionality to parse nodes
outside of DOM. Function ScanDOM in version 2 supports custom root node as
first parameter, but it needs testing.

**Comment by aminya** [comment]
This is my final HTML using the previous method
![image](https://user-images.githubusercontent.com/16418197/88476782-c927cd80-cf00-11ea-8039-a8b5cd057cb8.png)

If it needs to be created using DOM, I can do that too. It is pretty easy for this case.

**Comment by cyberalien** [comment]
Can you try it with version 2? `@iconify/iconify@beta`

**Comment by aminya** [comment]
Using DOM:
```js
import Iconify from '@iconify/iconify';
export async function createMDIIcon(iconName) {
  const icon = document.createElement("span")
  icon.classList.add("iconify")
  icon.setAttribute("data-icon", "ic:baseline-access-time")
  return icon
}
```
![image](https://user-images.githubusercontent.com/16418197/88476883-6f73d300-cf01-11ea-9f28-592cd465e86d.png)

**Comment by aminya** [comment]
I got it working using the beta version. Also, the `async` seems to cause some issues. I went `sync` here:
![image](https://user-images.githubusercontent.com/16418197/88477021-3b4ce200-cf02-11ea-8dc7-96d9d227097c.png)

**Comment by aminya** [comment]
Could you add this simple example to the documentation so others can use?

```js
import Iconify from '@iconify/iconify';


export function createIcon(iconName) {
  const icon = document.createElement("span")
  icon.classList.add("iconify")
  icon.setAttribute("data-icon", `${iconName}`)
  return icon
}

const icon = createIcon("ic:baseline-access-time") // gives your desired icon as an element

```

**Comment by cyberalien** [comment]
Good idea! Thanks

**Comment by aminya** [comment]
I will keep this close until you add those. Thanks!

**Comment by cyberalien** [comment]
Do you know of a very simple Atom package that I can play with, which won't require a lot of Electron/Atom knowledge to setup? I'd like to test Iconify behaviour in it.

**Comment by aminya** [comment]
I set up an environment for you.

1) install atom
2) dev this branch:
```
git clone --single-branch --branch iconify https://github.com/aminya/tool-bar.git
cd tool-bar
apm dev .
```
3) (if you like) install atom-ide-javascript
```
apm install atom-ide-javascript
```
4) Install the deps and fire up the rollup
```
npm install
npm run dev
```
5) open Atom in dev mode
```
atom --dev .
```
6) I set up the `lib/icon-service/iconify.js` for you to edit. This is the only file you need to care about.
7) To see the changes press (CTRL+SHIFT+F5) to reload Atom.
8) You can open Chrome's dev menu by (CTRL+Shift+P -> running "Window: toggle dev tools")

**Comment by cyberalien** [comment]
Thanks! Got it working.

2 missing commands:
```
apm install .
apm link
```
Not sure if first one was needed.

Unfortunately I couldn't debug it today, so will do it tomorrow. It is working!

**Comment by cyberalien** [comment]
I forgot that in version 2 I've already added function similar to createElement: renderSVG

```js
export function createIconElement(icon) {
  return Iconify.renderSVG(icon);
}
```

It will return null if icon does not exist, which would usually complicate things a bit, however because you also want offline usage, this is not an issue because icon should always exist.

If you want to make sure an element is always returned, even when icon is missing, use this:
```js
export function createIconElement(icon) {
  return Iconify.iconExists(icon) ? Iconify.renderSVG(icon) : document.createElement('span');
}
```

As for offline use, best option is to create a bundle.

In your test files I've made `build-iconify.js` in root directory that creates `lib/iconify-bundle.js`:
```js
const fs = require("fs");
const iconFinder = require("@iconify/json");

// Source file for Iconify
const iconifySource = "@iconify/iconify/dist/iconify.without-api";

// Bundle file
const outputFile = "./lib/iconify-bundle.js";

// Icon sets to load. Key = prefix in Iconify sets, value = prefix in output
const iconSets = {
  octicon: "octicon",
  ion: "ion",
  foundation: "fi", // Rename "foundation" to "fi"
  "icomoon-free": "icomoon", // Rename "icomoon-free" to "icomoon"
  mdi: "mdi",
  ic: "ic",
  "fa-brands": "fab", // Rename "fa-brands" to "fab"
  fa: "fa",
};

// Bundle Iconify
const resolvedIconify = require.resolve(iconifySource);
let bundle = fs.readFileSync(resolvedIconify, "utf8");

// Bundle icon sets
Object.keys(iconSets).forEach((prefix) => {
  const source = iconFinder.locate(prefix);
  if (!source) {
    throw new Error(`Unable to locate icon set "${prefix}"`);
  }
  const data = JSON.parse(fs.readFileSync(source, "utf8"));

  // Remove useless metadata
  ["info", "categories", "themes", "chars"].forEach((attr) => {
    delete data[attr];
  });

  // Change prefix
  data.prefix = iconSets[prefix];

  // Add to bundle
  bundle += "\nIconify.addCollection(" + JSON.stringify(data) + ");\n";
});

// Save bundle
fs.writeFileSync(outputFile, bundle, "utf8");
console.log(`Saved ${outputFile} (${bundle.length} bytes)`);

// Try to copy .d.ts
const tsSource = resolvedIconify.replace(".js", ".d.ts");
try {
  const tsContent = fs.readFileSync(tsSource);
  fs.writeFileSync(outputFile.replace(".js", ".d.ts"), tsContent);
} catch (err) {
  //
}
```
Install `@iconify/json` as dev dependency, run `node build-iconify`.

Then I've replaced `lib/icon-service/iconify.js` with this:
```js
import Iconify from "../iconify-bundle";

export function createIconElement(icon) {
  return Iconify.iconExists(icon) ? Iconify.renderSVG(icon) : document.createElement('span');
}

// the icon property will be passed into createIconElement automatically
export const testIcons = [
  { icon: "ic:baseline-access-time", color: "yellow" },
  { icon: "mdi:content-save", color: "red" },
];
```

Bundle is 7.35mb in size, which I think is reasonable considering that it includes multiple icon sets.

In `build-iconify.js` change icon sets list as needed. Because you have prefixes for icon sets that are sometimes different from ones used in Iconify, I've made variable `iconSet` and object, where key is Iconify prefix, value is prefix you want to use.

Few notes about icon sets:
- Do not use FontAwesome, especially version 4. Version 4 was imported from icon font, icons have very inconsistent spacing and might look terrible. Version 5 is better, but still doesn't follow any sensible grid. It is a badly designed icon set.
- IonIcons you've listed use "ios-" and "md-" prefixes. That's outdated version of IonIcons. New version no longer uses prefixes. Good news is Iconify icon set does include icons with those prefixes, so it will work. Iconify used to include those icons a while ago, crawler instead of removing icons makes them hidden, so old icons are always available in any icon set.

**Comment by cyberalien** [comment]
There are big changes in beta 4 that has just been released, which can solve your problem differently. You don't really need it, but I think it is worth mentioning if it helps anyone else to solve similar issue.

In original message you wanted Iconify to replace icons in node that isn't attached to DOM. It wasn't possible in old version because Iconify scanned only body. Now it is possible.

Method 1 can scan node once, do not watch it for changes: `Iconify.scan(node)`.

Method 2 will scan node and will observe it for changes: `Iconify.observe(node)`. To remove observer, use `Iconify.stopObserving(node)`.

**Comment by aminya** [comment]
@cyberalien Thank you so much! I will try these and will let you know how it goes
