### ISSUE TITLE
Allows adding additional `attributes` when using `getIconCSS`

### ISSUE THREAD

**Issue by hyoban** [iconify/iconify#303]
Add a new option to `getIconCSS`, so that we can add additional custom `attributes` to the output of the SVG url. Just pass it directly to `iconToHTML`.

 I am willing to submit a pull request for this change.

**Comment by cyberalien** [comment]
What would be the use case for it?

**Comment by hyoban** [comment]
Because https://github.com/egoist/tailwindcss-icons/issues/42

I'm trying to find a way to provide basic support for custom `stroke-width`. For icons that do not contain `stroke-width` in the body, this seems to be achieved by adding attributes on the SVG tag.

**Comment by cyberalien** [comment]
1. You can already do that by wrapping icon in `<g stroke-width="1.5">` and `</g>`
2. It affects only small subset of icons that use stroke and do not have `stroke-width` set. I can't think of any icons that it would apply to. Tabler Icons mentioned in linked issue has `<g stroke-width="1.5">` inside icon, so attribute on `<svg>` element will have no effect.

Since you are already passing icon data to `getIconCSS`, you can do all replacements and/or wrapping before passing icon data. That gives you full control, including replacing existing values,.

**Comment by hyoban** [comment]
Oh!!! Thank you very much for your reply. I should know how to deal with it.

**Comment by cyberalien** [comment]
Added option `customise` to new version of plugin.

Docs show this very specific use case - changing stroke width in Tabler icons.

New plugin: https://iconify.design/docs/usage/css/tailwind/iconify/customise.html
Plugin with dynamic selectors: https://iconify.design/docs/usage/css/tailwind/dynamic/customise.html

You can use multiple instances of plugin with different settings to have the same icons with different stroke width.

**Comment by sep2** [comment]
> You can use multiple instances of plugin with different settings to have the same icons with different stroke width.

Hi could you elaborate a bit on how to do this? Does this means different instances should have different prefixes?

**Comment by cyberalien** [comment]
This won't work with UnoCSS, it is only for Iconify plugin for Tailwind CSS.
