### ISSUE TITLE
Iconify - Definitely the easiest! Why not the fastest?

### ISSUE THREAD

**Issue by RykGitProjects** [iconify/iconify#314]
Hello,

I am using Iconify in my project with SvelteKit and it has been fantastic. Adding icons with just one line of code is incredibly convenient and efficient.

However, I've noticed a couple of performance drawbacks:
1. **JavaScript Dependency**: Icons require JavaScript to load, which means they do not work with server-side rendering (SSR).
2. **Multiple Network Requests**: Each icon is downloaded separately, leading to multiple network connections as seen in the dev tools.

I read the documentation on [Iconify Icon](https://iconify.design/docs/iconify-icon/), but it seems to still rely on external API connections, which doesn't address these issues.

I propose an enhancement inspired by Tailwind CSS's approach: automatically saving only the used icons to a `/static/SVGs` directory. This process could also leverage SVG sprites to further optimize performance. 

### Proposed Solution:
- **SVG Sprites**: Generate SVG sprites during the build process. This would allow the same icon to be used multiple times without adding significantly to the HTML payload.
- **Icon Scanning**: During the app build, scan for all used icon IDs. Create SVG sprites based on these icons, ideally creating a separate sprite per URL (SvelteKit folder).
- **SVG `<use>` Tag**: Utilize the `<use>` tag to reference icons within the sprite. This ensures that when the same icon is used multiple times on a page, it won't significantly increase the HTML size generated by SSR.
- **SSR Compatibility**: Ensure the icons work seamlessly with SSR, eliminating the need to wait for JavaScript and reducing cumulative layout shift.

This approach would align with the principles of Tailwind CSS and SvelteKit, combining ease of use with enhanced performance.

Thank you for considering this suggestion. I believe it would greatly improve the user experience by increasing loading speeds and reducing layout shifts.

Best regards,
Richard

**Comment by cyberalien** [comment]
That's a nice solution, but currently I have no plans to work on something like that. Especially not for SvelteKit because I'm not using it myself (prefer Nuxt), so I'm not familiar enough with it to develop such project.

However, using SVG sprites are bad idea, so it needs a different approach. Sprites fail to render for icons that contain any CSS or animations, making them unusable for some icons. Then there are bugs with scaling them in Chrome and Safari (reported when I was researching possibility to use sprites, but still not fixed in either browser), so only square icons work correctly. Should be avoided at all costs.

**Comment by RykGitProjects** [comment]
Thank you for detailed explanation!

**Comment by cyberalien** [comment]
Linking to bugs with SVG sprites, so in future if they do get fixed, this approach can be considered:
- Chrome bug (the biggest issue): https://issues.chromium.org/issues/40069098
- Safari bug (might be in Chrome too, but bug linked above prevents testing): https://bugs.webkit.org/show_bug.cgi?id=259970

The only browser that correctly handles sprites is Firefox.

However, even if those bugs are fixed, CSS in icons can cause bugs (CSS is an issue of simple conflict because scope is a sprite, not icon), animations can fail (didn't write it down when testing, so don't remember exact circumstances when this happens), so I will stay away from sprites in all projects.

**Comment by RykGitProjects** [comment]
How about without sprite? It won't be perfect as it would still have multiple connections. But it should still be better in my understanding as ssr would work fine producing plain html (thou better to use <use> not to duplicate svg code if there are multiple same icons on page)

**Comment by cyberalien** [comment]
Better solution is to just use icons in CSS. CSS is generated separately and cached, so loaded by visitors only once.

Plugin for Tailwind CSS can handle it. Additionally, all functions used by plugins are included in Iconify Utils package, so custom solution similar to plugin can be built.

**Comment by RykGitProjects** [comment]
Thank you. Unfortunatelly I am not that advanced. For now I moved to a couple of static svg's inside a code and a couple of most used once in /statis/SVGs

It improved page performance by a little bit
