### ISSUE TITLE
Nuxt Error while using @iconify-json/fluent-emoji

### ISSUE THREAD

**Issue by imrofayel** [iconify/iconify#326]
I encountered an error while working with @iconify-json/fluent-emoji. The error message is: 

 ```
ERROR  The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received 'file:///_entry.js'
```

Whenever I use this icon library and deploy on Vercel, deployment stop with this error.

```
Error: Command "npm run build" exited with SIGKILL
```

**Comment by cyberalien** [comment]
That's an issue with your code, not that package, completely unrelated.

Though one possibility comes to mind: could be an issue with some memory or size limitation somewhere. Fluent Emoji is the biggest icon set by huge margin, icons contain a lot of filters to make those shiny gradients which makes average icon about 30kb (for comparison, average size of icon in most other sets is below 1kb). I wouldn't use that icon set anywhere because vector icons are so huge.

**Comment by imrofayel** [comment]
> That's an issue with your code, not that package, completely unrelated.
> 
> Though one possibility comes to mind: could be an issue with some memory or size limitation somewhere. Fluent Emoji is the biggest icon set by huge margin, icons contain a lot of filters to make those shiny gradients which makes average icon about 30kb (for comparison, average size of icon in most other sets is below 1kb). I wouldn't use that icon set anywhere because vector icons are so huge.

**Comment by genu** [comment]
I ran into this as well.

@cyberalien to your point, it is code related, but usually on the side of library authors, in dev user land.

Here, for example: https://stackblitz.com/edit/github-t63qxl

running `pnpm build`

fails because the project depends on `nuxt-ui` which depends on `nuxt-icon` which then tries to bundle the JSON icons during build, causing a Memory error.

Although this isn't a bug, per se, but it is a side effect that can easily be extremely difficult the debug.

Maybe a note should be added somewhere.

I'll open up an issue on this edge case on `nuxt-icon` repo
