### ISSUE TITLE
error import cheerio

### ISSUE THREAD

**Issue by ridhopanca** [iconify/iconify#328]
![image_2024-08-10_162943878](https://github.com/user-attachments/assets/c2e198b7-7e68-4c3b-8ef0-e49024399fb3)

**Comment by cyberalien** [comment]
Not sure what's going on there. My guess is some dependency imports old version of cheerio package, which would trigger that error.

**Comment by ridhopanca** [comment]
My mistake, created an issue here, which was a dependency error in astro-icon, I found a temporary solution there, thank you.

**Comment by cyberalien** [comment]
Noticed that cheerio was set to fixed version `1.0.0-rc12` in dependencies, since then version `1.0.0` was released that broke types.

Published version `4.0.5` that updates to latest cheerio and fixes types.

Related bug report (and a workaround, which is currently used in Iconify Tools update) in cheerio repo: https://github.com/cheeriojs/cheerio/issues/3988
