### ISSUE TITLE
once the animation done it doesnt restart

### ISSUE THREAD

**Issue by xalteropsx** [iconify/iconify#329]
when the icon animate first time it work fine when next time come it dont animate again

also i cant find a any docs regarding ur iconify animate

**Comment by cyberalien** [comment]
I guess you are talking about icons with animated stroke from Material Line Icons set: https://github.com/cyberalien/line-md

Those icons run animation only once when it is rendered.

I'm not sure what you mean by "when next time come it dont animate again". Are you hiding and showing icon or re-creating it or what do you mean by that?

**Comment by cyberalien** [comment]
UnoCSS renders icons as background and mask images.

There is a big bug in browsers when using icons like that: animation timer starts when icon is first loaded. So first time you render icon, timer start and icon is animated. If you render same icon later again, timer already started, so animation has finished.

Additionally, soft refresh in browser does not reset animation timer if icon is cached, so after soft refresh animation doesn't restart either.

Unfortunately, Chrome team doesn't want to fix that. I've filed a bug report few years ago, Chromium dev told me it is like that by design.

Solution is to use `iconify-icon` web component: https://iconify.design/docs/iconify-icon/

I'm using it on all websites, including Nuxt and Vitepress. It has a workaround for that bug, correctly animating icons every time it is rendered. Additionally, it re-animates icon whenever it appears in view (this can be disabled [using noobserver prop](https://iconify.design/docs/iconify-icon/#rendering-only-visible-icons))
