### ISSUE TITLE
An transparent div appears on the Chrome browser

### ISSUE THREAD

**Issue by leookun** [iconify/iconify#356]
Users cannot click on any buttons because it is obscured by this element.
![image](https://github.com/user-attachments/assets/0120a245-4efc-48a2-b20e-836accb401e0)

**Comment by cyberalien** [comment]
What Chrome extensions are you using?

There is no such element on website, so it was added by some extension.

Try disabling extensions one by one to figure out which one is causing it, report it as bug to that extension. Also please tell me which extension is causing it because it is likely someone else will encounter same problem.

**Comment by leookun** [comment]
I checked extensions, it was caused by the keepassxc-browser

**Comment by cyberalien** [comment]
Thanks!

Installed that extension, was able to reproduce bug. CSS fix works.

**Comment by cyberalien** [comment]
And now fixed properly, so extension can work without issues.
