### ISSUE TITLE
use in Vanilla JS

### ISSUE THREAD

**Issue by xiki808** [iconify/iconify#39]
Can the icons work without any JS frameworks?

I installed @iconify/iconify package, but I'm stuck at how to use it.

**Comment by cyberalien** [comment]
I'm not sure what you are looking for. Do you mean you want raw SVG files for icons?

**Comment by xiki808** [comment]
Sorry for not describing my issue properly. I would like to use this framework in my JS without a JS framework. 

With this React package: https://github.com/iconify/iconify/tree/master/packages/react

After installing the packages we can import the Icon component and the icon itself and use it in JSX.

I cannot use the React Icon component ( or at least i think ) in my plain JS web component to render the icon.

This is an example of web component I am working on:

```
import { LitElement, html } from 'lit-element';

import styles from './styles';

export default class MenuItem extends LitElement {
  constructor() {
    super();
    this.item = [];
  }

  static get properties() {
    return {
      item: {},
    };
  }

  render() {
    return html`
      <a href="#" class="icon-btn">
      </a>
    `;
  }

  static get styles() {
    return styles;
  }
}

customElements.define('my-menu-item', MenuItem);
```

Hope I made myself clear, if you need any more information please let me know. I would really like to use this framework.

**Comment by cyberalien** [comment]
So you need something like React component, but without React dependency?

**Comment by xiki808** [comment]
Yes! Also because I tried the React package but it didn't work for me ( could be I miss how I should integrate it though! ).

**Comment by cyberalien** [comment]
You can use SVG framework. It has no dependencies.

Documentation: https://docs.iconify.design/implementations/svg-framework/

By default, SVG framework is designed to replace `span` elements with `svg`. If you use that method, it is as simple as using `span` tags. SVG framework will take care of everything else.

If you want to render entire HTML without placeholders, like React component does, you can do that too, but it is a bit more complex.

Complexity depends on how you want icons to load. There are 2 options:
- Loading icon data dynamically from API.
- Bundling icons (similar to React component).

If you prefer first option, it becomes a bit more complex because loading is asynchronous. You can either render placeholder element and wait for SVG framework to do replacements or you can use `loadIcons()` callback (or async version based on Promise that you can find in loadIcons documentation): https://docs.iconify.design/implementations/svg-framework/load-icons.html

If you prefer second option, it is easier because icon data is available immediately. However you need to bundle icons. Creating icon bundles is very easy. Here is documentation and example bundle scripts that you can use: https://docs.iconify.design/sources/bundles/ and here is documentation for using SVG framework without API: https://docs.iconify.design/implementations/svg-framework/without-api.html

Is this what you are looking for?

**Comment by xiki808** [comment]
Was hoping for something similar in use to React's package, but I guess I don't know what I'm asking for!

This will do yes! I can follow the code along in the examples, thank you.

**Comment by cyberalien** [comment]
You can use it similar to React's package.

You can import Iconify like a package. You can also import icons one by one, like in React, then add them by name:
```js
import Iconify from '@iconify/iconify`;
import home from '@iconify/icons-mdi-light/home';

Iconify.addIcon('mdi-light:home', home);

// Creates 'svg' element
const svg = Iconify.renderSVG('mdi-light:home', {});

// Creates string that you can use as innerHTML or parent element
const html = Iconify.renderSVG('mdi-light:home', {});
```
renderSVG: https://docs.iconify.design/implementations/svg-framework/render-svg.html
renderHTML: https://docs.iconify.design/implementations/svg-framework/render-html.html

**Comment by xiki808** [comment]
Thanks that got me figured out!

`renderSVG` and `renderHTML` were not available for me, yarn installed version 1. But I worked it out using `getSVG` function instead.

Is there anyway how these icons can be imported dynamically. For example I have an array of icons, coming from the client and would like to load and use just those. I see there is a `getCollection` function but I'm not sure what to pass as JSON parameter, could this help?

Also really sorry for closing the issue!

**Comment by cyberalien** [comment]
You can use array of icons as parameter to `loadIcons()` function and wait for callback. See examples in https://docs.iconify.design/implementations/svg-framework/load-icons.html

As for version 1, it is a bit harder to implement there because load function doesn't have a callback. Old version used events instead that are a bit tricky to use. I suggest avoiding version 1, use version 2 instead.

If Yarn installs version 1, try `yarn add @iconify/iconify@beta` or `yarn add @iconify/iconify@2`

**Comment by xiki808** [comment]
Thank you for your constant replies! 

I am running on beta.6 now and `loadIcons` function is not found. Hopefully it's not me getting super tired.

**Comment by xiki808** [comment]
Oh I'm using iconfiy without API, maybe that's why, I'm checking.

**Comment by cyberalien** [comment]
Yes, that would be reason why? loadIcons loads icons from API, so it doesn't exist in version without API.

**Comment by xiki808** [comment]
Wow! This is beautiful 😃 

For  those who might be reading this: A bit tricky was caching as always, but `loadIcons` solves that with the callback. The component needs to rerender on callback and if loaded, _and_ this callback happens for each icon collection in use.

Super neat and easy! Thank you for this project!
