### ISSUE TITLE
web-component implementation

### ISSUE THREAD

**Issue by obonyojimmy** [iconify/iconify#62]
First congrats !  Id like to propose addition of web-component implementation which i think will be an added bonus .

**Comment by cyberalien** [comment]
I think it would be good idea to implement it, but it will take some time because it is not a priority right now.

Implementing basic component similar to `@iconify/react` as web component is rather pointless - better to just use SVGs. 

Implementing component with API support that takes icon name as attribute and loads data from API (similar to SVG framework and `@iconify/react-with-api`) is something I do want to do, but due to time limitations is not an option right now. First I need to finish new website and publish all new components and SVG framework that are currently marked as release candidates waiting for website to be complete.

**Comment by cyberalien** [comment]
This took a while...

Icon web component is finally available: https://www.npmjs.com/package/iconify-icon

It is still in development, so version number starts with 0, but can probably be used in production because all code it uses is shared with stable SVG framework and components for frameworks like React.

It is massive improvement over old framework specific components. Performance of icons in shadow DOM is much better, especially complex icons that use animations.

Documentation is missing, but it is basically the same as other components. You can pass icon as `icon` attribute or property. To pass an object with icon data instead of icon name, you can either `JSON.stringify()` it or use property instead of attribute (technically same thing: property is just a setter that stringifies object).
