### ISSUE TITLE
Is there a way to use these icons with SvelteKit?

### ISSUE THREAD

**Issue by SamuelEarl** [iconify/iconify#67]
I get errors when I try to use these with SvelteKit due to SSR. I can still use these icons in my app if I use the HTML option.

Thank you.

**Comment by cyberalien** [comment]
What exactly are you trying to use? SVG framework? Svelte component?

**Comment by SamuelEarl** [comment]
I was trying to use [Iconify for Svelte](https://github.com/iconify/iconify/tree/master/packages/svelte), but I actually really like the plain HTML and CSS options that are displayed after you select an icon. They work with SSR, so I think I am good. Thank you.

**Comment by silasabbott** [comment]
For any that come across this, I had this issue and it's also noted in #69.

I was installing my icons with `-D` and `--save-dev` to install them as development dependancies only like I do in Vue. If you install the `@iconify-icons` packages as normal dependancies without the `--save-dev` flag, they'll work.

It works but it's unfortunate because it defeats the purpose of importing them all separately—all your icons are now bundled with the production app.

**Comment by cyberalien** [comment]
Latest version of Svelte component can load icons data from Iconify API, so no need to bundle icons anymore. 

Install it with `@alpha` tag: 
```bash
npm install --save-dev @iconify/svelte@alpha
```

Then use icon by name without importing any additional packages:
```jsx
<Icon icon="mdi:home" />
```

Documentation has already been updated for new version, just need to finish rewriting main website (which also uses Svelte component) before publishing all new components as stable: https://docs.iconify.design/icon-components/svelte/

**Comment by tv42** [comment]
I feel like the only solution being "use our CDN" just isn't great. I for one literally *need* an offline development setup.

**Comment by cyberalien** [comment]
Then you are posting in wrong ticket.

There are several offline solutions, but this ticket is not about that. See https://docs.iconify.design/icon-components/svelte/offline.html

**Comment by tv42** [comment]
Yet, that doesn't seem to work with SvelteKit and SSR...

**Comment by cyberalien** [comment]
Have you actually tried it? Because it does work and new version of https://icon-sets.iconify.design/ is actually a Svelte app with SSR.

Though I did experience few issues building it, but those issues were caused by bugs in Svelte server side rendering, not by icon component. More specifically, I've ran into bug hydrating components and I've ran into bug preventing Svelte from compiling component from node_modules for server side rendering.
