### ISSUE TITLE
Provide documentation on how to change icon after it loaded

### ISSUE THREAD

**Issue by visurel** [iconify/iconify#7]
After an icon is loaded with the default: `<span class="iconify" data-icon="noto:bird"></span>` it's not easily possible to change this icon into another one. It looks like iconify does not react to any further changes to the data-icon attribute. I tried changing the data-icon attribute using JS (specifically Angular, but it's more a general thing) after an icon is loaded, but it just stays the same and nothing happens. 

Any guidance on how one should do this or is this an improvement you would consider?

**Comment by cyberalien** [comment]
To change icon you need to replace entire element with new placeholder. So replace it with new `span`.

After icon has been loaded, its no longer a `span`, it is `svg`. That is not a valid placeholder element, so it is not watched for changes.

Watching attributes would also complicate things a lot because there are multiple ways to set icon name: `data-icon` attribute and `icon:noto:bird` in list of classes. Also older browsers that unfortunately some visitors still use become very slow when watching DOM for attribute changes.

I have limited knowledge of Angular, but I did test similar code in React. React renders new element when any attribute is changed instead of changing old element, which causes Iconify to render new icon with new attributes. Doesn't Angular behave like that as well?

**Comment by visurel** [comment]
Thanks for the quick reply!
Sadly Angular doesn't create a new element, it binds directly to the attribute with `[attr.data-icon]="icon"` and only changes that part, without re-rendering, as far as I know and tested. Thing is, with Angular I haven't found a way to render the icon in a good fashion, just some dirty hacking with `*ngIf` and `*ngFor` around it to force it to re-render. If there are any plans on developing the Angular framework for Iconify, I'd be happy to provide assistance, as Iconify goes really well with Angular Material. 👍

**Comment by cyberalien** [comment]
I'd love to make Angular component, similar to React component: https://github.com/iconify/iconify-react

Problem is components system in Angular seems very complex to me. Saw few tutorials online, they were either outdated or very complex. All I need is example of how to render basic element with some attributes, like `<custom-component text="whatever" />` then I can use it to use icon attribute and render SVG. For me rendering SVG is the easy part, figuring out how components work in Angular is tricky.

**Comment by cyberalien** [comment]
Idea for temporary workaround: render different elements. For one icon its `span`, for other icon its `i`. Maybe that will force Angular to render completely new component.

**Comment by visurel** [comment]
I saw that the iconify-react component renders the SVG completely independent, am I right? It does not require the iconify.js file from your CDN? If we would implement the same in Angular, I think the issue would disappear, because I think Angular is just confused (some directives seem to not work correctly), because you directly replace the element and Angular wants to keep control over everything. If you're interested I can get you started with a clean library repository, it was hard in the past, but it got easier, basically Angular-CLI can handle all now. Would it basically be the same code as for the iconify-react? I could also try to take that as a starting point.

**Comment by visurel** [comment]
FYI: I created a "draft" version of an Angular component for Iconify (it works as far as I tested, but I call it draft, because I'm not sure if all functionality is implemented + it's relying heavily on the SVG class from the iconify-react)
https://github.com/visurel/iconify-angular

**Comment by cyberalien** [comment]
This is awesome.

As for functionality, it seems to accept transformation, size and color attributes, so that's all functionality there is.

You can also take a look here: https://github.com/vuetifyjs/vuetify/issues/7821#issuecomment-512699068
This is different type of implementation. React component is independent from Iconify script. That code is Vue component that is built around Iconify script, so it loads icons from API. Maybe you can use something from that too.

**Comment by visurel** [comment]
Okay great!
I think the React component already is really great, having the SVG "inline" bundled with the application through the @iconify/icons-* packages is really convenient and good for performance. I'll further test the component in some projects and see if there's anything I missed, but so far it looks promising and works really great.

**Comment by cyberalien** [comment]
icons- packages are published by custom script based on Iconify Tools package. It updates collections-json repositories and publishes icons- packages. Script is fully automated and is ran 1-2 times per day.

Iconify Tools are available here: https://github.com/iconify/tools and in NPM as @iconify/tools

Iconify Tools can import icons and export them in various formats. Export for icons- packages is in src/export/component.js
