### ISSUE TITLE
IconifyConfig for v2.0

### ISSUE THREAD

**Issue by arjendejong12** [iconify/iconify#71]
Hi,

Could you tell me what the new 2.0 api is for adding your own provider?
Based on this issue #4 I'm using the following JavaScript:
```js
IconifyConfig = { localStorage: true, defaultAPI: 'https://iconify.[...].nl/{prefix}.js?icons={icons}' }
```
However, this doesn't work for v2.0.

**Comment by cyberalien** [comment]
Thanks for bringing this up! I've just noticed that API configuration is not included in documentation and will fix it as soon as possible.

Version 2 has completely changed how API is handled. There are several reasons for it:

1. Instead of old config string that assumed all data is retrieved using JSONP, new version uses Fetch API if browser supports it. In config it stores domain and optional path, not full URL.
2. API supports fallback domains. So if icons can't be retrieved from API within 750ms (default value, can be configured), it attempts to retrieve icons from secondary API. 
3. Multiple API providers can be configured. Icons now have optional namespace, like `@custom:icon-prefix:icon-name`, where `custom` is API provider. Each provider has different configuration. This allows anyone to host their own icon sets instead of hosting all icons.
4. In addition to SVG framework, native components for various frameworks (React, Vue, Svelte) now support API. They also work on server side (can be done by including cross-fetch and using setFetch function), not just in browser. They are currently published as alpha versions, but I'm already using them in my work and they are very stable.

You can configure API before loading SVG framework or after it. To do it before, use `IconifyProviders` variable. It is a simple object, where key is provider (empty string for default provider), value is partial API config. Example:
```js
IconifyProviders = {
  // Configuration for default API provider
 '': {
     resources: ['https://iconify.whatever.nl']
 }
}
```

You can also configure API after loading, but make sure it is done synchronously, so code is bundled with SVG framework instead of being loaded from separate file.
```js
Iconify.addAPIProvider('', {
  resources: ['https://iconify.whatever.nl']
});
```
Everything has been rewritten in TypeScript and types are exported, so you should get hints for config options in your code editor.

**Comment by arjendejong12** [comment]
@cyberalien Thank you for your quick response! Your first code example worked for me. Good to know I can still set my own provider without a fallback.
