### ISSUE TITLE
Release tags

### ISSUE THREAD

**Issue by uok** [iconify/iconify#82]
Big thanks to all devs and contributors - this is a great project! :tada: 

It would be great if you add release tags here on Github for easier version tracking.

I also noticed two small bugs:
+ on your website it says `https://code.iconify.design/2/2.0.3/iconify.min.js` 
in your [latest commit](https://github.com/iconify/iconify/commit/02ccf588171fac6a6690be3792c54241956061d4) it says `https://code.iconify.design/2/2.0.4/iconify.min.js`
+ there is no version info in the header of iconify.min.js

Keep up the good work! :smile:

**Comment by cyberalien** [comment]
Thanks!

It makes sense to have tags for single package repositories, but this is a monorepo that includes multiple different packages. There are multiple packages: SVG framework, React component, Svelte component, Vue components, Ember addon and few helper packages. All have different version numbers because they are published independently. React package is on major version 3 right now, while Vue 2 is on 1.

Website is a mess, updating anything there is far from simple process and it badly needs rewriting. So some data there is out of date. I'm slowly moving everything to automated continuous integration, so all parts would be updated automatically, but it will take a while.

Including version number in header is a good idea! Bundler can easily handle that.

**Comment by cyberalien** [comment]
As of next version, build process will add version number to header.
