### ISSUE TITLE
suggest to make a single package for all the packages of @iconify-icons

### ISSUE THREAD

**Issue by sktanwar2014** [iconify/iconify#88]
hi team, i'm using @iconify-icons in my application but when the currect icon exist on other package that is annoying to install package again & again for each icon which exist in different npm package.
so i just want to suggest make a common package for all the @iconify-icons's icons. i'm sure after this there will be good increasing in @iconify-icons users.

**Comment by cyberalien** [comment]
That would be a mess because there are over 100k icons.

There are few other solutions:
1. Generate icon you need yourself.
2. Use https://github.com/antfu/unplugin-icons which installs icon packages as needed and generates those files.

To generate files yourself, you need to install all icon sets: `@iconify/json` package, then use one of these options:

1. Install `@iconify/utils` package and use it to get data for icons you need: https://docs.iconify.design/tools/utils/get-icon-data.html
2. Generate bundles: https://docs.iconify.design/sources/bundles/

Bundles tutorial is a bit outdated, it relies on `@iconify/json-tools` package, which works, but doesn't have typings, so has been replaced by `@iconify/utils` package. Updating documentation to new code is in todo list.

**Comment by cyberalien** [comment]
Documentation has been rewritten.

Also Iconify Tools have been rewritten, now it has a function to generate NPM packages for icon sets, so packages can be easily created for custom icon sets.
