### ISSUE TITLE
proposal: add option to load custom icons from external sources

### ISSUE THREAD

**Issue by userquin** [iconify/iconify#96]
We are trying (@antfu and me) to make a universal toolkit to share some logic to allow load svg icons from any source on `unocss` and `unplugin-icons`. 

Instead creating a shared repo to use it on both projects, I think the better place will be here: this way you can also use it for testing before adding new collections or new icons to existing collections.

The logic to be included here, right now, is only supported on `unplugin-icons`:
- load from external sources (network or filesystem): currently only built-in support for filesystem with optional  transform callback for all icons
- load from inline sources: all collections and their icons on the configuration

The main problem here is that all collection/icon  loading logic is not asynchronous: 
- https://github.com/iconify/iconify/blob/master/packages/utils/src/icon-set/get-icon.ts
- https://github.com/iconify/iconify/blob/master/packages/utils/src/icon-set/get-icons.ts

On `unplugin-icons` we load the collections/icons using async tasks:
- https://github.com/antfu/unplugin-icons/blob/main/src/core/modern.ts#L57
- https://github.com/antfu/unplugin-icons/blob/main/src/core/modern.ts#L25

/cc @cyberalien

**Comment by cyberalien** [comment]
I'm not sure why you would want getIcon and getIcons to be asynchronous. They do not retrieve anything, functions only parse data that is already available, thus there is nothing in those functions to make asynchronous.

**Comment by userquin** [comment]
uhmm, yeah, sorry  (too many things), we want to allow this: https://github.com/antfu/unplugin-icons#custom-icons

What we want to add here (using some utilities from Anthony's repos): 
- [InlineCollection](https://github.com/antfu/unplugin-icons/blob/69f90a00c8cff1b6a42ae6ecc7a5377163b53875/src/types.ts#L5)
- [CustomIconLoader](https://github.com/antfu/unplugin-icons/blob/69f90a00c8cff1b6a42ae6ecc7a5377163b53875/src/types.ts#L4)
- [FileSystemIconLoader](https://github.com/antfu/unplugin-icons/blob/69f90a00c8cff1b6a42ae6ecc7a5377163b53875/src/loaders.ts#L6)

**Comment by cyberalien** [comment]
Sure, that can be done.

However, I have few concerns:

1. If types are to be added to utils, there should be code that works with those types, so functions that use it should be added as well.
2. Utils should not have any dependencies, except for types. It is meant to be a package that can be used in any environment. Helper functions such as `camelize` and `pascalize` can be added to utils. `Awaitable` type can be imported. Node specific functions, such as ones that work with file system, should be isolated in separate files to make sure they are not imported by accident.

**Comment by userquin** [comment]
@cyberalien this should go to `master` or `dev/branch`?

**Comment by cyberalien** [comment]
I've just made new branch `dev/more-utils` from `master`

**Comment by cyberalien** [comment]
Ignore it.

This repo is not a usual monorepo, it is managed by `lerna`, which makes things a bit tricky. Unfortunately usual mono repo approach doesn't work here because multiple packages use different versions of same dependency, such as Vue 2 and Vue 3 components, which also have different versions of testing environment. So each package has its own node_modules, its own package-lock.json and `lerna` messes up `package-lock.json` each time it is ran.

So installation order (I'll update readme to make it clearer):
- `npm install` in root folder to install `lerna`. Can skip it if you have `lerna` installed globally.
- `npm run bootstrap` which will install dependencies for each package and create symbolic links.

If you run `npm install` in one of packages, it might replace symbolic links with actual package from NPM, so run `npm run link` from root directory to fix all symbolic links.

It is a mess, there are hundreds of opened issues at `lerna` repository about that, but looks like it is no longer maintained and I don't know of a different solution that can work with multiple versions of same package. If you do know a better solution, please post it because I would love to dump `lerna` for something more modern.

Until then all changes to `package-lock.json` files can be ignored. Commit them or restore old file - doesn't matter because it will be changed anyway.

**Comment by userquin** [comment]
done
